name: DABI Core Official Signed Build

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK and AAB
      run: ./gradlew assembleRelease bundleRelease

    # Hatalardan arındırılmış resmi imzalama adımı
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: "" # Boş bırakıyoruz, ana dizindeki dabi.jks dosyasını okuyacak
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }} # Hatalı girdi düzeltildi
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0" # Eksik olan zipalign hatasını çözmek için güncel sürüme çekildi

    - name: Upload Official Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: dabi-resmi-imzali-apk
        path: app/build/outputs/apk/release/*-signed.apk

    - name: Upload Official Signed AAB (Google Play)
      uses: actions/upload-artifact@v4
      with:
        name: dabi-resmi-imzali-aab
        path: app/build/outputs/bundle/release/*.aab
